### ISSUE TITLE
The timings appear to be generated in Debug

### ISSUE THREAD

**Issue by mattgallagher** [quickbirdstudios/CombineRxSwiftPerformance#1]
In Release builds, the Combine timings are about the same (since Combine is shipped as a Release build from Apple) but the RxSwift timings are roughly 3-5 times faster.

**Comment by grafele** [comment]
Thank you for pointing this out. I have updated the readme file and mentioned that. I will update the graphs as soon as I habe access to my Mac. 

Since I saw you critique about the reasonability of the tests I invite you to create a pull request and add your own tests. As mentioned in the first few sentences: We use RxSwifts own test suite for these tests and they should therefore not be biased in the direction of Combine.

**Comment by grafele** [comment]
@mattgallagher Source Code, numbers and statistics are updated. I will take some time later this day and see if I can add more tests with your description in mind.
Thanks for your feedback again!
